### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by ttll0363** [EliasNehme/NPPC#2]
Thanks for your interesting work, is the data used for training available?

**Comment by EliasNehme** [comment]
Yes. In the paper, we only used open-source datasets: 
- MNIST: http://yann.lecun.com/exdb/mnist/
- CelebAHQ: https://mmlab.ie.cuhk.edu.hk/projects/CelebA/CelebAMask_HQ.html
- Bioimage translation dataset from ZeroCostDL4Mic: https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/pix2pix
